# CodeRabbit AI Code Review Configuration
# Documentation: https://docs.coderabbit.ai/configuration

language: "en-US"

reviews:
  # Skip review for deployment branches
  base_branches:
    - "!gh-pages"

  # Automatic review on PR open
  auto_review:
    enabled: true
    # Review on each push to PR
    auto_incremental_review: true
    # Ignore draft PRs
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
      - "DRAFT"

  # Review profile: chill | assertive
  profile: "assertive"

  # Tone instructions
  tone_instructions: |
    Be direct and technical. Focus on security issues, error handling,
    and shell scripting best practices. Skip praise and pleasantries.
    Provide specific line references and ShellCheck codes when applicable.

    This project uses emoji conventional commits (e.g., "✨ feat:", "🐛 fix:").
    Do not suggest removing emojis from commit messages or PR titles.

  # Path-specific instructions
  path_instructions:
    - path: "scripts/**/*.sh"
      instructions: |
        Review shell scripts for:
        - POSIX compatibility issues
        - Security vulnerabilities (command injection, unquoted variables)
        - Error handling (missing error checks, unchecked exit codes)
        - ShellCheck warnings (SC1091, SC2034, SC2086 are intentionally ignored)
        - Proper quoting of variables
        - Use of safe patterns (printf -v instead of eval)

        IMPORTANT: This project uses a modular shell architecture where all scripts
        in scripts/ directory (00-init.sh through 99-main.sh) are concatenated in
        numeric order by GitHub Actions to produce a single pve-install.sh file.
        Functions defined in earlier scripts (e.g., 06-utils.sh, 08-wizard-core.sh,
        12-wizard-main.sh) are available in later scripts. Do NOT flag function
        calls as "undefined" if the function exists in another numbered script file.
        All scripts share global variables and functions after concatenation.
    - path: "templates/**"
      instructions: |
        Review templates for:
        - Placeholder consistency ({{PLACEHOLDER}} format)
        - Valid configuration syntax
    - path: "tests/**/*.sh"
      instructions: |
        Review test scripts for:
        - Test coverage completeness
        - Proper assertions usage
        - Edge case handling

  # Skip files from review
  path_filters:
    - "!**/*.md"
    - "!.github/**"
    - "!LICENSE"

chat:
  # Allow commands in PR comments
  auto_reply: true
