coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 85%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false

ignore:
  - "spec/**/*"
  - "templates/**/*"
